FAQ/urls.py
from django.urls import path

from .views import FAQList,AddFAQ

urlpatterns = [
    path('', FAQList, name='FAQ'),
    path('add/',AddFAQ, name='add-faq')
]

Main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import Home.urls as Home
import Course.urls as Course
import FAQ.urls as FAQ
import Auth.urls as Auth
import Dashboard.urls as Dashboard
import Profile.urls as Profile
import Quiz.urls as Quiz
import Example.urls as Examples
import admins.urls as admins

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(Home)),
    path('Course/',include(Course)),
    path('FAQ/',include(FAQ)),
    path('Dashboard/',include(Dashboard)),
    path('Profile/',include(Profile)),
    path('Quiz/',include(Quiz)),
    path('Auth/',include(Auth)),
    path('Example/',include(Examples)),
    path('Only/Admin/',include(admins)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quiz/urls.py
from django.urls import path
from .views import KuisListView, viewkuis, kuis_data_view, save_kuis_view, PreQuiz , LiveQuiz, AddQuizPoint

app_name = 'Quiz'

urlpatterns = [
    path('', KuisListView.as_view(), name='halaman-kuis'),
    path('<pk>/',PreQuiz ,name='pre-quiz'),
    path('<pk>/save/', save_kuis_view, name='save-view'),
    path('<pk>/data/', kuis_data_view, name='kuis-data-view'),
    path('<pk>/doing/<soal>/', LiveQuiz, name='live-quiz'),
    path('addPoint/', AddQuizPoint, name='add-quiz-point'),
]

Quiz/models.py
from django.db import models
from User.models import Account
from Course.models import Course
class Kuis(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    banyaksoal = models.IntegerField(default=1)
    lulus = models.IntegerField(help_text="Score minimal lulus %")
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING, null=True, blank=True)
    
    def __str__(self):
        return f"{self.name}-{self.topic} - {self.pk}"

    def get_questions(self):
        return self.soal_set.all()[:self.banyaksoal]
    
    class Meta:
        verbose_name_plural = 'Kuisis'


class Soal(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Kuis, on_delete=models.CASCADE)
    dibuat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{str(self.text)} - {self.pk}'
    
    def getanswer(self):
        return self.jawaban.all()

class Answer(models.Model):
    text = models.CharField(max_length=200)
    betul = models.BooleanField(default=False)
    tanya = models.ForeignKey(Soal, on_delete=models.CASCADE, related_name='jawaban')
    dibuat = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"pertanyaan: {self.tanya.text}, jawaban:{self.text}, benar: {self.betul}"

class Result(models.Model):
    quiz = models.ForeignKey(Kuis, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

Quiz/views.py
from django.shortcuts import render
from .models import Kuis, Soal, Answer, Result
from django.views.generic import ListView
from django.http import JsonResponse
#Refrensi https://dev.to/chukslord1/building-a-quiz-app-with-django-and-fauna-2ojo
#Refrensi https://medium.com/swlh/overview-building-a-full-stack-quiz-app-with-django-and-react-57fd07449e2f

from .models import Kuis, Soal, Answer, Result
from json import dumps
from django.http import JsonResponse

class KuisListView(ListView):
    model = Kuis
    template_name = 'Quiz.html'

def viewkuis(request, pk):
    kuis = Kuis.objects.get(pk=pk)
    return render(request, 'Kuisnya.html', {'obj':kuis})

def kuis_data_view(request, pk):
    kuis = Kuis.objects.get(pk=pk)
    soal = []
    for q in kuis.get_questions():
        jawaban = []
        for a in q.get_answers():
            jawaban.append(a.text)
        soal.append({str(q): jawaban})
    return JsonResponse({
        'data': soal,
    })

def save_kuis_view(request, pk):
    if request.is_ajax():
        soal2 = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        for k in data_.keys():
            soal = Soal.objects.get(text=k)
            soal2.append(soal)
        user = request.user
        kuis = Kuis.objects.get(pk=pk)

        score = 0
        multiply = 100/ kuis.banyaksoal
        results = []
        correct_answer = None

        for q in soal2:
            a_select = request.POST.get(q.text)
            if (a_select != ""):
                jawaban_soal = Answer.objects.filter(tanya=q)
                for a in jawaban_soal:
                    if (a_select == a.text):
                        if a.betul:
                            score+=1
                            correct_answer = a.text
                        else:
                            if a.betul:
                                correct_answer = a.text
                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_select}})
            else:
                results.append({str(q): 'not answered'})
        score_ = score * multiply
        Result.objects.create(kuis=kuis, user=user, score=score_)

        if (score_ >= kuis.lulus):
            return JsonResponse({'pass':True, 'score':score_, 'results': results})
        else:
            return JsonResponse({'pass':False,'score':score_, 'results': results})


def PreQuiz(request, pk):
    CurrentQuiz = Kuis.objects.get(pk=pk)
    print(CurrentQuiz)
    response = {
        'navbar':'white',
        'footer' :'black',
        'namakuis' : CurrentQuiz.name,
    }
    return render(request, 'PreQuiz.html',response)

def LiveQuiz(request, pk, soal):
    CurrentQuiz = Kuis.objects.get(pk=pk)

    All_Soal = Soal.objects.all()
    CurrentSoal = []
    for i in All_Soal:
        if(i.quiz == CurrentQuiz):
            CurrentSoal.append(i)
    
    if(int(soal) > int(CurrentQuiz.banyaksoal)):
        response = {
            'navbar':'white',
            'footer' :'black',
            'lenSoal' : len(CurrentSoal),
         }
        return render(request, 'QuizFinish.html',response)

    

    indexes = int(int(soal)- 1)
    soal_now = CurrentSoal[indexes]
    soal_description = f'No {soal} of {CurrentQuiz.banyaksoal}'
    All_Answer = Answer.objects.all()
    CurrentAnswer = []

    for i in All_Answer:
        if(i.tanya == soal_now):
            CurrentAnswer.append(i)
    print(CurrentAnswer)
    response = {
        'navbar':'white',
        'footer' :'black',
        'namakuis' : CurrentQuiz.name,
        'numbering' : soal_description,
        'soal' : soal_now,
        'answers' : CurrentAnswer,
    }

    return render(request, 'LiveQuiz.html',response)


def AddQuizPoint(request):
    print(request.POST)
    return JsonResponse(request,{
        'Succes': 'ok'
    })

Quiz/templates/Kuisnya.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{obj.name}}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/quiz.css'%}">
{% endblock %}

{% block content %}
    {{obj.name}}
    <p>Minimal kelulusan: {{obj.lulus}}%</p>
    <hr>
    <a href="{% url 'Quiz:halaman-kuis' %}" class="btn btn-danger">Back to Quiz List</a>
    <form id="form-kuis" class="mt-3 mb-3">
        {% csrf_token %}
        <div id="box-kuis"></div>
        <button type="submit" class="btn btn-primary mt-3">Simpan</button>
    </form>s
    <div id="scoresc"></div>
    <div id="resultsc"></div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/soal.js' %}" defer></script>
{% endblock %} 

Quiz/templates/LiveQuiz.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{namakuis}}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/livequiz.css'%}">
{% endblock %}

{% block content %}
<div class="wrapper-quiz">
    <div class="container container-fluid p-5 soal-container">
        <div class="numbering">
            <p>{{numbering}}</p>
        </div>

        <div class="soal">
            <p>{{soal.text}} ? </p>
        </div>

        <div class="options">

            {% for answer in answers %}
            <div class="answers">
                <p class="currentAnswer" id="{{answer.betul}}" onClick="AnswerQuiz()" >{{answer.text}}</p>
            </div>
            {% endfor %}
                
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'js/livequiz.js' %}"></script>
{% endblock %}

Quiz/templates/PreQuiz.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{namakuis}}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/quiz.css'%}">
{% endblock %}

{% block content %}
<div class="wrapper-quiz">
    <div class="container container-fluid prepare">
        <div class="loading-bar">
            <p>{{namakuis}}</p>
            <div class="loader">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div class="pre-message">
                <p>Please wait</p>
                <p>Fetching your request</p>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'js/prequiz.js' %}"></script>
{% endblock %}

Quiz/templates/Quiz.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Quiz
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/quiz.css'%}">
{% endblock %}

{% block content %}
  <!-- Diambil dari https://getbootstrap.com/docs/5.1/components/modal/ -->
  <div class="modal fade quiz-wrapper" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Mulai?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body-confirm">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tidak</button>
          <button type="button", id="start-button" class="btn btn-success">Ya</button>
        </div>
      </div>
    </div>
  </div>

  <div class="h1">Quiz List</div>
  <hr>
  {% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-question="{{obj.banyaksoal}}"
        data-lulus="{{obj.lulus}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button>
  {% endfor %}

{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'js/quiz.js' %}" defer></script>
{% endblock %} 

Quiz/templates/QuizFinish.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Finish
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/finishQuiz.css'%}">
{% endblock %}

{% block content %}
<div class="wrapper-quiz">
    <div class="container container-fluid p-5 quiz-finish">
       <div class="congrats">
           <p>Finished !</p>
       </div>
       <div class="fire-container">
            <canvas class="fireworks" width="300" height="300"></canvas>
       </div>

       <div class="result">
        <!-- Button trigger modal -->
        <div class="modal-result">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                See Result
              </button>
              
              <!-- Modal -->
              <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle" style="color:black;">Quiz Result</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                        <div class="result-container">
                            <p class="correct-answer">Correct Answer : </p>
                            <p class="wrong-answer">Wrong Answer : </p>
                            <p class="Message"></p>
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-primary" onClick="BackToCourse()">Go back to course</button>
                    </div>
                  </div>
                </div>
              </div>
              
        </div>
       </div>

       <p class="banyak-soal" style="display:none;">{{lenSoal}}</p>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'js/finishQuiz.js' %}"></script>
{% endblock %}